name: 📦 Build and Release

on:
  push:
    paths:
      - lib/justifi/version.rb
  workflow_dispatch:

jobs:
  run_tests:
    name: 📋 Verify
    uses: justifi-tech/justifi-ruby/.github/workflows/verify.yml@main
    if: github.ref == 'refs/heads/main'
    secrets:
      CLIENT_STAGING_ID: ${{secrets.CLIENT_STAGING_ID }}
      CLIENT_SECRET_STAGING: ${{secrets.CLIENT_SECRET_STAGING }}
      API_STAGING_BASE_URL: ${{secrets.API_STAGING_BASE_URL}}
      ENVIRONMENT: ${{secrets.ENVIRONMENT}}

  build_and_release:
    strategy:
      matrix:
        include:
          - api_key: JUSTIFI_MACHINA_RUBYGEMS_API_KEY
            bearer: false
            gem_host: https://rubygems.org
            pkg_host_name: rubygems.org
          - api_key: JUSTIFI_MACHINA_GITHUB_TOKEN
            bearer: true
            gem_host: https://rubygems.pkg.github.com/${{ github.repository_owner }}
            pkg_host_name: pkg.github.com

    name: 📦 Package and Release on ${{ matrix.pkg_host_name }}
    needs: run_tests
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Build API_KEY value
        id: api_key
        run: |
          echo "::set-output name=value::${{ matrix.bearer && 'Bearer ' || '' }}${{ secrets[matrix.api_key] }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
          rubygems: 3.2.32 # Required for GEM_HOST_API_KEY to work (delete if we use Ruby 3)

      # The `computed` value here is to solve for `-pre` style tags.
      # `raw_value` is what comes directly from the VERSION value, and
      # `computed` is what `Gem::Version` will output
      - name: Fetch Gem Version
        id: gem_version
        run: |
          ruby -r ./lib/justifi/version.rb -e '
            puts "::set-output name=raw_value::#{Justifi::VERSION}"
            puts "::set-output name=computed::#{Gem::Version.new(Justifi::VERSION)}"
          '

      # Combination of bundler's release steps and the steps here:
      #
      #   https://github.com/rickstaa/action-create-tag/blob/main/entrypoint.sh
      #
      - name: Tag Release
        id: git_tag
        if: matrix.gem_host == 'https://rubygems.org' # only do this step 1 time
        env:
          TAG: v${{ steps.gem_version.outputs.raw_value }}
          VERSION: ${{ steps.gem_version.outputs.raw_value }}
          GITHUB_TOKEN: ${{ secrets.JUSTIFI_MACHINA_GITHUB_TOKEN }}
        run: |
          git config user.name "JustiFi Machina"
          git config user.email "justifi.machina@justifi.ai"
          git tag -a "${TAG}" -m "Version ${VERSION}" "${GITHUB_SHA}"
          git remote set-url origin "https://justifi-machina:${{ secrets.JUSTIFI_MACHINA_GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin refs/tags/${TAG}

      - name: Build gem
        run: gem build justifi.gemspec

      - name: Publish gem to GitHub packages
        env:
          GEM_HOST_API_KEY: ${{ steps.api_key.outputs.value }}
          RUBYGEMS_HOST: ${{ matrix.gem_host }}
          VERSION: ${{ steps.gem_version.outputs.computed }}
        run: |
          gem push --host ${RUBYGEMS_HOST} justifi-${VERSION}.gem
